### ISSUE TITLE
I can help you to make your site look much better

### ISSUE THREAD

**Issue by Anmol-Prasad** [earthtoyash/earthtoyash.github.io#1]
Hi Yash, I have over 2 years experience in web development and I have created tons of beautiful and responsive sites as my personal projects and for clients . I would love to improve your site as well . So can you assign this project to me?

**Comment by earthtoyash** [comment]
I have already assigned it to someone else. But you can also do a pull request if you want. If your design is better, I will merge it. No pressure :)
