### ISSUE TITLE
Background image is repeating 

### ISSUE THREAD

**Issue by codemaniac-sahil** [earthtoyash/earthtoyash.github.io#21]
Hello @earthtoyash, I checked your website and I found that background image of website is repeating vertically.

**Comment by earthtoyash** [comment]
If you can fix it then fix it please, I will accept the committed PR and merge it.
-------- Original Message --------

**Comment by codemaniac-sahil** [comment]
Okay @earthtoyash, first please assign me this case.

**Comment by codemaniac-sahil** [comment]
And also label this issue with hacktoberfest

**Comment by codemaniac-sahil** [comment]
@earthtoyash check, I just create the PR.

**Comment by SidAsif** [comment]
Hey @earthtoyash, I am new to open source and want to contribute on this !!!
please assigned it to me..

**Comment by codemaniac-sahil** [comment]
@SidAsif, this issue is already resolved.

**Comment by earthtoyash** [comment]
Agreed

**Comment by codemaniac-sahil** [comment]
@SidAsif, you can also contribute in my repos.
