### ISSUE TITLE
Elements are small

### ISSUE THREAD

**Issue by codemaniac-sahil** [earthtoyash/earthtoyash.github.io#22]
Whole page elements are small when viewed in small screens.

**Comment by earthtoyash** [comment]
Yeah

**Comment by codemaniac-sahil** [comment]
would you please add hacktoberfest labels.

**Comment by earthtoyash** [comment]
Hacktoberfest label is already added on the repo.

**Comment by codemaniac-sahil** [comment]
during accepting PR you should add label of hacktoberfest-accepted

**Comment by codemaniac-sahil** [comment]
I think

**Comment by codemaniac-sahil** [comment]
Would you please assign this issue to me.

**Comment by earthtoyash** [comment]
Okay

**Comment by codemaniac-sahil** [comment]
Thank you @earthtoyash

**Comment by earthtoyash** [comment]
I added the label, can you confirm?

**Comment by codemaniac-sahil** [comment]
Yes, @earthtoyash It is showing

**Comment by earthtoyash** [comment]
Awesome
