### ISSUE TITLE
Add a Contributing.md file.

### ISSUE THREAD

**Issue by RathoreAbhiii** [earthtoyash/earthtoyash.github.io#25]
This repository needs to have a Contributing.md file in order to be eligible for Hacktoberfest 2022. You can create and update the repository with the same or assign me this issue as I would love to work on it! Thanks!

**Comment by earthtoyash** [comment]
It's all yours now, happy hacktoberfest :)

**Comment by devilkiller-ag** [comment]
Hey can I work on this?

**Comment by RathoreAbhiii** [comment]
> Hey can I work on this?

@earthtoyash could you please assign this issue to @devilkiller-ag as I have already completed a similar issue in a different repo.

**Comment by earthtoyash** [comment]
> Hey can I work on this?
> 

I am sorry, he was the first. Happy Hacktoberfest :)

**Comment by earthtoyash** [comment]
Issue is assigned now. Hurry up! Happy hacktoberfest :)
